export const CLIENT_KAFKA_NAME = 'appNest';

export enum Env {
  PORT = 'PORT',
  DATABASE = 'DATABASE',
  DATABASE_HOST = 'DATABASE_HOST',
  DATABASE_PORT = 'DATABASE_PORT',
  DATABASE_USERNAME = 'DATABASE_USERNAME',
  DATABASE_PASSWORD = 'DATABASE_PASSWORD',
  KAFKA_BROKER = 'KAFKA_BROKER',
  KAFKA_TOPIC = 'KAFKA_TOPIC',
  KAFKA_GROUP_ID = 'KAFKA_GROUP_ID',
  JWT_SECRET_KEY = 'JWT_SECRET_KEY',
  JWT_EXPIRES_IN = 'JWT_EXPIRES_IN',
  CREDENTIAL_USERNAME = 'CREDENTIAL_USERNAM',
  CREDENTIAL_PASSWORD = 'CREDENTIAL_PASSWORD',
}
